export default {
  locale: 'en',
  messages: {
    siteTitle: 'TOBCITY, share your expenses',
    addTravel: 'Add travel',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Trip',
    createNewPost: 'Create new trip',
    from: 'City where you are',
    to: 'City you are going',
    date: 'Date of your trip',
    plate: 'License Plate of your car',
    price: 'Price for each person',
    model: 'Year of the car',
    submit: 'SUBMIT',
    comment: 'What your passengers should know',
    logout: 'Log Out',
    loginface: 'Log in with Facebook',
    logingoogle: 'Log in with Google',
    cellphonelogin: 'Log in with your cellphone number',
  },
};
