export default {
  locale: 'es',
  messages: {
    siteTitle: 'TOBCITY divide tus gastos',
    addTravel: 'Agregar Viaje',
    switchLanguage: 'Cambiar Idioma',
    twitterMessage: 'Estamos en twitter',
    by: 'Por',
    deletePost: 'Eliminar Viaje',
    createNewPost: 'Crear nuevo Viaje',
    from: 'Ciudad de partida',
    to: 'Ciudad de destino',
    date: 'Date of your trip',
    plate: 'Placa de tu carro',
    price: 'Precio por persona',
    model: 'Modelo del carro',
    submit: 'Publicar',
    comment: 'Que otras cosas deben saber los pasajeros',
    logout: 'Salir',
    loginface: 'Ingresa con Facebook',
    logingoogle: 'Ingresa con Google',
  },
};
